-- 009_shadow_outcomes.sql
--
-- DATA_ENGINE_PLAN.md V1 — the shadow-outcome tracker (proxy "silver" training labels).
--
-- After each REAL discovery run, every hard-gate SURVIVOR (bought or not) is enqueued here; a
-- weekly job re-pulls its Keepa stats at day-30 and day-60 checkpoints and records whether it
-- WOULD have profited at the ORIGINAL simulated landed cost (frozen at enqueue). These are proxy
-- labels: they IGNORE execution and sell-through (we never actually bought/sold), so they are a
-- weaker signal than a realized (gold) outcome and MUST be reported as their own tier in every
-- calibration report that uses them (labels.py label_quality='silver').
--
-- Time-sensitivity is the whole point: a shadow label takes 30 days to mature, so every day the
-- scout runs without enqueueing candidates is a day of silver data that can never be recovered.
--
-- NOT-APPLIED pattern (like migrations 001-008): additive-only. scout/shadow_outcomes.py and the
-- db.py helpers degrade to a no-op/empty until this lands. Apply via the Supabase SQL editor or
-- the Supabase MCP when ready. Every downstream reader tolerates its absence.

CREATE TABLE IF NOT EXISTS shadow_outcomes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asin                TEXT NOT NULL,
    candidate_run_id    BIGINT,                 -- runs.id of the discovery run that surfaced it
    checkpoint_day      INT NOT NULL,           -- 30 | 60
    enqueued_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at              TIMESTAMPTZ NOT NULL,   -- enqueued_at + checkpoint_day days
    -- "then" snapshot (frozen at enqueue) --------------------------------------------------
    landed_cost         NUMERIC,                -- ORIGINAL simulated landed cost (price_then * cogs frac)
    price_then          NUMERIC,
    offers_then         INT,
    sales_rank_then     INT,
    weight_lb           NUMERIC,                -- for the fee math at recheck (doesn't change)
    category            TEXT,                   -- referral-rate lookup at recheck
    features_snapshot   JSONB,                  -- PRE_DECISION_FEATURES only (leakage-safe training input)
    -- "now" snapshot (filled at the checkpoint recheck) -----------------------------------
    price_now           NUMERIC,
    offers_now          INT,
    sales_rank_now      INT,
    would_have_profited BOOLEAN,                -- net_proceeds(price_now) - landed_cost > 0
    est_profit_now      NUMERIC,
    status              TEXT NOT NULL DEFAULT 'pending',  -- pending | done | error
    computed_at         TIMESTAMPTZ,
    UNIQUE (asin, candidate_run_id, checkpoint_day)   -- one row per candidate per checkpoint (idempotent enqueue)
);

ALTER TABLE shadow_outcomes ENABLE ROW LEVEL SECURITY;
-- service_role only, matching every other business table (no anon/public policy).

-- The weekly recheck selects pending rows whose checkpoint has come due.
CREATE INDEX IF NOT EXISTS shadow_outcomes_due_idx ON shadow_outcomes (status, due_at);
