-- 010_backtest_rows.sql
--
-- DATA_ENGINE_PLAN.md V2 — the backtest engine's output: DERIVED feature rows only (never raw
-- Keepa histories — those live in the data lake). Each row is one simulation window: the exact
-- pre-decision feature snapshot the live pipeline would have computed at `simulation_date` using
-- ONLY history strictly before it, plus the observed label at simulation_date + horizon (default
-- 60 days): would_have_profited at the simulated landed cost.
--
-- These are the 4th and WEAKEST label tier (label_quality='backtest', below silver): they are
-- hindsight simulations on historical market data, with no execution, no sell-through, and a
-- simulated buy cost. They MUST carry their own tier line in any report and are never blended
-- silently into gold/silver (labels.py enforces the tier; V3's ranker trains on backtest+silver
-- +gold with graded relevance, but calibration reports separate them).
--
-- Volume: ~50k rows is the target first corpus (3-5k ASINs x ~10 windows each). Split BY ASIN,
-- never by row (an ASIN's windows must never straddle a train/validation boundary — enforced in
-- code + tested, not here).
--
-- NOT-APPLIED pattern (like 001-009): additive-only; scout/backtest.py + db.py helpers degrade to
-- a no-op/empty until this lands. Apply via the Supabase SQL editor or MCP when ready.

CREATE TABLE IF NOT EXISTS backtest_rows (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asin                TEXT NOT NULL,
    simulation_date     DATE NOT NULL,          -- the as-of date features were computed at
    horizon_days        INT NOT NULL DEFAULT 60,
    features_snapshot   JSONB NOT NULL,         -- PRE_DECISION_FEATURES only, computed as-of (leakage-safe)
    landed_cost         NUMERIC,                -- simulated buy-in at simulation_date (price_then * cogs frac)
    price_then          NUMERIC,
    offers_then         INT,
    price_at_horizon    NUMERIC,
    offers_at_horizon   INT,
    est_profit          NUMERIC,                -- net_proceeds(price_at_horizon) - landed_cost
    would_have_profited BOOLEAN,                -- est_profit > 0
    label_quality       TEXT NOT NULL DEFAULT 'backtest',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (asin, simulation_date)              -- idempotent: re-running a window overwrites, never dupes
);

ALTER TABLE backtest_rows ENABLE ROW LEVEL SECURITY;
-- service_role only, matching every other business table (no anon/public policy).

-- Read pattern: pull the whole set for training (labels.py _from_backtest); split BY ASIN in code.
CREATE INDEX IF NOT EXISTS backtest_rows_asin_idx ON backtest_rows (asin);
