-- 012_trends_series.sql
--
-- Session 55 (2026-07-06) — free signal-type features: weekly Google Trends interest points per
-- tracked term (brand or category). scout/signals/trends.py owns fetching (pytrends, unofficial
-- API — backoff + jitter, cache-first) and feature computation (interest_now_vs_90d_avg,
-- slope_4wk, seasonal_z, spike_flag), all read from this table via db.trends_series_for().
--
-- Vocabulary: every brand seen recently in leads/deal_hints (capped ~200, db.
-- recent_brand_vocabulary) + the ~10 learning.sampling categories (ai-brain.json).
--
-- NOT-APPLIED pattern (like 001-011): additive-only; scout/db.py's upsert_trends_series/
-- trends_series_for degrade to 0/[] until this lands, so nothing else breaks in the meantime.
-- Apply via the Supabase SQL editor or MCP when ready.

CREATE TABLE IF NOT EXISTS trends_series (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term        TEXT NOT NULL,           -- a brand name or a learning.sampling category key
    term_kind   TEXT NOT NULL,           -- 'brand' | 'category'
    week_start  DATE NOT NULL,           -- the Trends weekly bucket's start date
    interest    NUMERIC NOT NULL,        -- 0-100 relative search interest (Google Trends scale)
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (term, week_start)            -- idempotent: re-fetching a week overwrites, never dupes
);

ALTER TABLE trends_series ENABLE ROW LEVEL SECURITY;
-- service_role only, matching every other business table (no anon/public policy).

CREATE INDEX IF NOT EXISTS trends_series_term_idx ON trends_series (term, week_start);
