-- 013_ranker_runs_and_tier_columns.sql
--
-- Session 57 (2026-07-09) — the control-center's new "Scout intelligence" charts (backtest_rows
-- growth, per-run tier/token breakdown, ranker accuracy over time) need durable, queryable
-- history that didn't exist before this migration:
--
--   1. ranker_runs — one row per scout/train_ranker.py training run (cloud or local). Until now
--      the champion/challenger AUC + verdict only ever existed in two PLACES THAT DON'T LAST:
--      learning-hub/tracking/ranker-report.md (only updated by LOCAL runs — train-ranker.yml's
--      own header comment: the cloud run's copy lives on the ephemeral GitHub Actions runner and
--      is never committed back) and a Discord post (#brain-proposals, human-readable but not
--      queryable). A live run on 2026-07-08 23:45 UTC trained on 550 rows and produced a real
--      champion AUC of 0.72 that NO durable, queryable record captured. This table is that
--      record — train_ranker.py inserts a row every time it actually trains (never on a
--      skip-if-unchanged tick), independent of whether the .md file or Discord post succeed.
--   2. runs.tier1_tokens / tier2_tokens / tier3_tokens / backtest_rows_written /
--      backtest_asins_sampled — collect_hourly.py's run_hourly_collect() already computes these
--      per hourly burst (shadow rechecks / hint-led scan / backtest sampling+history-pull) but
--      only ever printed them to the ephemeral GitHub Actions log — nothing durable recorded
--      which tier got how much of the token budget, or how many rows a given run actually wrote.
--      Additive columns on the existing `runs` table (same row already written per run), so no
--      new join is needed to chart tier allocation or rows-written history.
--
-- NOT-APPLIED pattern (like 001-012): additive-only; scout/db.py's new helpers degrade to a
-- no-op/empty until this lands. Apply via the Supabase SQL editor or MCP when ready.

CREATE TABLE IF NOT EXISTS ranker_runs (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trained_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    host                      TEXT,                    -- 'github-actions-hourly' | local hostname
    refused                   BOOLEAN NOT NULL DEFAULT false,
    refusal_reason            TEXT,                    -- set only when refused
    row_count                 INT,                      -- training_set_fingerprint's row_count
    train_rows                INT,
    train_asins               INT,
    val_rows                  INT,
    val_asins                 INT,
    champion_auc              NUMERIC,
    champion_winners_in_top   INT,
    challenger_auc            NUMERIC,
    challenger_winners_in_top INT,
    verdict                   TEXT,
    by_tier                   JSONB,                    -- label-tier composition, e.g. {"backtest": {...}}
    by_source                 JSONB                     -- sampling-source AUC breakdown (dealfeed/explore/onpolicy)
);
ALTER TABLE ranker_runs ENABLE ROW LEVEL SECURITY;
-- service_role only, matching every other business table (no anon/public policy).

CREATE INDEX IF NOT EXISTS ranker_runs_trained_at_idx ON ranker_runs (trained_at);

ALTER TABLE runs ADD COLUMN IF NOT EXISTS tier1_tokens INT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS tier2_tokens INT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS tier3_tokens INT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS backtest_rows_written INT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS backtest_asins_sampled INT;
