"""
scout/memory_report.py — measures whether brand memory (Prompt S3) actually improves the
analyst's disagreement calls (Scout Agent Build Plan sec 4's "measurement harness").

Honest per the plan's own flag: "measurable gains for this exact domain are unproven." This
report does not assume memory helps — it compares the disagreement-to-bad-outcome hit rate
between leads scored WITH a memory note available (analyst_note.memory_used == True) and
WITHOUT one, and says "not enough data yet" until both groups clear a real sample size. Never
edits ai-brain.json or any scout data.
"""
from __future__ import annotations

import datetime as dt
import os
from typing import Any, Dict, List, Optional

import db
import labels

HERE = os.path.dirname(os.path.abspath(__file__))
REPORT_PATH = os.path.join(HERE, "..", "learning-hub", "tracking", "memory-effectiveness-report.md")

# Two groups need a real sample each — half of labels.min_labeled_rows()'s usual bar (30),
# since this splits the same pool of leads in two.
MIN_SAMPLE_PER_GROUP = 15


def _outcome_label(lead: Dict[str, Any]) -> Optional[bool]:
    outcomes = lead.get("outcomes") or []
    if not outcomes:
        return None
    outcome = sorted(outcomes, key=lambda o: o.get("closed_at") or "", reverse=True)[0]
    return labels.label_from_outcome(outcome)


def _group_by_memory_used(leads: List[Dict[str, Any]]):
    """Only leads where the analyst pass actually ran (memory_used is explicitly present) are
    comparable — a lead that predates Prompt S1, or where the analyst was unavailable, has no
    memory_used flag and is excluded from both groups rather than silently miscounted."""
    with_memory, without_memory = [], []
    for lead in leads:
        note = (lead.get("explanation") or {}).get("analyst_note") or {}
        if "memory_used" not in note:
            continue
        (with_memory if note["memory_used"] else without_memory).append(lead)
    return with_memory, without_memory


def disagreement_hit_rate(leads: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """Among leads where the analyst disagreed with the rules AND a realized outcome exists,
    what fraction turned out bad (i.e. the disagreement was a useful warning)? None if there
    are no such disagreements in this group yet."""
    hits, total = 0, 0
    for lead in leads:
        note = (lead.get("explanation") or {}).get("analyst_note") or {}
        if not note.get("disagrees_with_rules"):
            continue
        label = _outcome_label(lead)
        if label is None:
            continue
        total += 1
        if label is False:  # the disagreement correctly flagged a bad outcome
            hits += 1
    if total == 0:
        return None
    return {"hit_rate": round(hits / total, 3), "n": total}


def generate_report() -> str:
    leads = db.leads_with_outcomes()
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [f"## {now} — memory effectiveness check", ""]

    with_memory, without_memory = _group_by_memory_used(leads)
    if len(with_memory) < MIN_SAMPLE_PER_GROUP or len(without_memory) < MIN_SAMPLE_PER_GROUP:
        lines.append(f"Not enough data yet to compare (with-memory n={len(with_memory)}, "
                     f"without-memory n={len(without_memory)}; need >={MIN_SAMPLE_PER_GROUP} "
                     f"each). Expected until Prompt S1 has run for a while with S3 memory "
                     f"notes available for some brands and not others.")
        lines.append("")
        return "\n".join(lines)

    with_stats = disagreement_hit_rate(with_memory)
    without_stats = disagreement_hit_rate(without_memory)
    lines.append(f"With-memory group (n={len(with_memory)}): "
                 f"{with_stats if with_stats else 'no disagreements with a realized outcome yet'}")
    lines.append(f"Without-memory group (n={len(without_memory)}): "
                 f"{without_stats if without_stats else 'no disagreements with a realized outcome yet'}")
    lines.append("")
    lines.append("Honest caveat (Scout Agent Build Plan sec 4): no published study covers "
                 "memory's effect on LLM-analyst accuracy for OA specifically — this is a "
                 "direct A/B measurement on OUR data, not a literature-backed guarantee "
                 "either way.")
    lines.append("")
    return "\n".join(lines)


def write_report() -> str:
    block = generate_report()
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    header = ("# Memory-effectiveness report (append-only)\n\n"
             "Generated by `scout/memory_report.py` (Scout Agent Build Plan Prompt S3 sec 4). "
             "Compares the analyst's disagreement-accuracy with vs without a brand memory "
             "note. Read-only — never edits ai-brain.json or any scout data.\n\n")
    if not os.path.exists(REPORT_PATH):
        with open(REPORT_PATH, "w", encoding="utf-8") as f:
            f.write(header)
    with open(REPORT_PATH, "a", encoding="utf-8") as f:
        f.write(block + "\n---\n\n")
    return block


if __name__ == "__main__":
    print(write_report())
